main.tf
Since `google_compute_ssl_certificate` cannot be updated after creation,
attempting to modify the `private_key` or `certificate` of the `google-lb-http`
will fail.  That is because the generated certificate cannot be
destroyed/created (to affect the change) while bound to its `target_https_proxy`.
By using `name_prefix` instead of `name`, a new certificate is generated
and attached to the `target_https_proxy`.
The `create_before_destroy` ensures that a certificate remains attached
to the `target_https_proxy` through the plan's application.
This does have a "breaking change" in that the SSL certificate name
is now computed rather than hard-coded.
=> Enable the replacement of `private_key` and `certificate` (#21)

main.tf, variables.tf
This adds the ability to pass a self_link of a [google_compute_security_policy](https://www.terraform.io/docs/providers/google/r/compute_security_policy.html) to be attached to the `backend_service` that this module manages.
Note that `google_compute_security_policy` is in beta. I wasn't sure if that blocks adding support for it. In testing, this worked as expected:
Usage:
* Assuming the `compute_security_policy` from the compute_security_policy [documentation](https://www.terraform.io/docs/providers/google/r/compute_security_policy.html):
```
resource "google_compute_security_policy" "policy" {
name = "my-policy"
rule {
action   = "deny(403)"
priority = "1000"
match {
versioned_expr = "SRC_IPS_V1"
config {
src_ip_ranges = ["9.9.9.9/32"]
}
}
description = "Deny access to IPs in …
```
=> Add security_policy support

main.tf, variables.tf
Adding variable CDN with default value false and add the enable_cdn option in the google_compute_backend_service.
=> adding cdn activation option

examples/.gitignore, examples/shared-vpc/README.md, examples/shared-vpc/example.tfvars, examples/shared-vpc/gceme.sh.tpl, examples/shared-vpc/main.tf, examples/shared-vpc/mig.tf, examples/shared-vpc/outputs.tf, examples/shared-vpc/variables.tf, main.tf, variables.tf
This PR improves support for using the module in a Shared VPC model, with instances in a service project and firewall rules in a host project.
- Introduces a `firewall_projects` variable for specifying the (host) projects to create firewall rules in
- Adds an example of working with the variables in a Shared VPC setup
=> Better support for Shared VPC (example and firewall rules)

main.tf
Removes duplicate `count` parameter on the `google_compute_firewall.default-hc` resource.
The firewall for the health check is intended to be created in all networks listed in the `firewall_networks` variable. So the number of rules is `length(var.firewall_networks) * length(var.backend_params)`. The [`element()`](https://www.terraform.io/docs/configuration/interpolation.html#element-list-index-) function automatically wraps for indexes out of range.
Fixes #7 
Fixes #27
=> remove duplicate count in firewall rule for backend health check

main.tf
This change sets the `ports` list to [""] when `backend_params` is empty.
Ideally this would be done with an expression like:
```
"${length(var.backend_params) == 0 ? "" : element(split(",", element(var.backend_params, count.index)), 2)}"
```
But because of a limitation with HCL, it cannot be done and we've resorted
to the trick described in this issue:
https://github.com/hashicorp/hil/issues/50#issuecomment-320078816
The pipe `|` delimiter is used because it is not valid to use in GCP names.
Contributed according to the Google CLA.
=> fix failure when no backend specified (#8)

README.md
One of the last changes in PR #52 (Terraform 0.12 compatibility) was to make all of these attributes required, or explicitly set to null if we do not want to change the default values.
The implementation across the example code was updated, but it looks like this entry in the README was missed
=> Update README with new "backends" syntax

variables.tf
Spotted #54 under the 2.0.0 milestone, and thought I'd take a look to see what's involved to properly handle the 'region' variable.
Turns out none of the resources that this module builds take 'region' as an argument, so it's an entirely unnecessary variable.
Looking back through the history of the codebase, 'region' came along the very first commit in this repository (ef1e5ccff515636de6560bb72fef93e8624cac43)... although it wasn't used then either! 🤷‍♂️
=> Remove unused region variable

CHANGELOG.md, README.md
This branch adds a CHANGELOG with an entry for 2.0.0 and placeholders for all of the previous releases, and adds a Terraform 0.12 compatibility note to the README. I would like to wait for #57 before releasing 2.0.0 but we've been sitting on this work for too long.
=> Create CHANGELOG.md and prepare 2.0.0 release

README.md, main.tf
This addresses #34. 
When setting up a configuration with:
```hcl
backend_protocol = "HTTPS"
```
Running `terraform apply` produces this error message:
> google_compute_backend_service.default: Error creating backend service: googleapi: Error 400: Invalid value for field 'resource.healthChecks[0]': 'https://www.googleapis.com/compute/v1/projects/setjemesian-terraform-admin/global/httpHealthChecks/web-lb-backend-0'. This HTTPS/HTTP2 backend service supports HealthCheck and HttpsHealthCheck, invalid
This is because the module is generating an `HttpHealthCheck`, but when `backend_protocol` is "HTTPS" you have to use an `HttpsHealthCheck` or a `HealthCheck` (arbitrary TCP port).
This PR resolves that by loading one of the other, depending on the state of `backend_protocol`.
I have tested this …
=> Use HTTPS health check when using HTTPS protocol to backend

CONTRIBUTING.md
While trying to get the integration test suite running I ran into several errors where APIs or permissions were not granted. This clarifies that in the documentation.
=> Clarify CONTRIBUTING about the permissions/APIs needed to get started

Makefile, README.md, build/int.cloudbuild.yaml, build/lint.cloudbuild.yaml
- fix #66 (when the cloud-foundation-toolkit PR is merged and new devtools version is released)
- [build] Update devtools image to generic major version for auto-update.
- Generate readme using fixed transform_docs script from this PR: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/449
=> Update devtools and fix generated readme

CHANGELOG.md, test/fixtures/mig_nat/main.tf, test/fixtures/multi_certs/main.tf, test/fixtures/multi_mig/main.tf, versions.tf
Fixes #75 
Similar to the GKE update for 3.x providers, relax the constraint `>= 2.15, <4.0`  and inside tests use the latest 3.5 provider version (test setup for creating project/iam still uses 2.x provider).
WIP on getting tests passing, e2e tests seem flaky/failing for me locally.
=> Allow 3.x google provider

main.tf
The two IP removed are for Network Load Balancer. From the document of
HTTPs Load Balancer, they are not needed.
https://cloud.google.com/load-balancing/docs/https/https-load-balancer-example?authuser=0#configuring_firewall_rules
=> Remove unnessary firewall source IPs.

README.md, autogen/README.md, autogen/main.tf.tmpl, autogen/variables.tf.tmpl, examples/https-gke/main.tf, examples/mig-nat-http-lb/main.tf, examples/multi-backend-multi-mig-bucket-https-lb/main.tf, examples/multi-mig-http-lb/main.tf, examples/multiple-certs/main.tf, examples/shared-vpc/main.tf, main.tf, modules/dynamic_backends/README.md, modules/dynamic_backends/main.tf, modules/dynamic_backends/variables.tf, variables.tf
Fixes #85
This a breaking change. For new versions of the modules, `log_config` block in each `backend` is required.
=> Add default log_config in google_compute_backend_service.

CHANGELOG.md, CONTRIBUTING.md, README.md, autogen/README.md, autogen/main.tf.tmpl, autogen/versions.tf.tmpl, docs/upgrading-v2.0.0-v3.0.0.md, docs/upgrading_to_v4.0.md, examples/multi-backend-multi-mig-bucket-https-lb/README.md, examples/multiple-certs/README.md, main.tf, modules/dynamic_backends/README.md, modules/dynamic_backends/main.tf, modules/dynamic_backends/versions.tf, test/fixtures/mig_nat/main.tf, test/fixtures/multi_certs/main.tf, test/fixtures/multi_mig/main.tf, versions.tf
Create a new local `backends_with_healthchecks` that represents all non global NEG backend services which are iterated over (as opposed to the full map of backends) to create the health check resources.
Furthermore if the value of `health_check` is null, an empty array is passed to the `compute_backend_service`'s `health_checks` argument.
Also includes linting of markdown files, as such please ignore whitespace changes for a better review experience.
fixes #105
=> fix: optionalize health check to support global NEG backend services

README.md
The example under "Usage" was incorrectly missing an equals sign after `iap_config` which is not valid.
=> Syntax correction to example in README.md

README.md, autogen/main.tf.tmpl, autogen/variables.tf.tmpl, examples/https-gke/main.tf, examples/https-redirect/main.tf, examples/mig-nat-http-lb/main.tf, examples/multi-backend-multi-mig-bucket-https-lb/main.tf, examples/multi-mig-http-lb/main.tf, examples/multiple-certs/main.tf, examples/shared-vpc/main.tf, main.tf, modules/dynamic_backends/README.md, modules/dynamic_backends/main.tf, modules/dynamic_backends/variables.tf, variables.tf
This PR allows attach armor security policy to specific backend service of the loadbalancer, allows usage of different security policies on a single lb with multiple backends.
=> Allow security policies per backend

README.md, autogen/main.tf.tmpl, main.tf, modules/dynamic_backends/main.tf, variables.tf
* Updates the per-backend `security_policy` fallback value to be the "global" value defined
in the module's variables i.e., `var.security_policy` rather than `null`.
1. Inherit `var.security_policy` when the `backend.security_policy` is `null`.
2. Explicitly set no security policy on a backend by setting `backend.security_policy` to `""` i.e., empty string.
* https://github.com/terraform-google-modules/terraform-google-lb-http/issues/130
1. `make build`
1. `make docker_test_lint`
1. Test using my forked branch in my code with only the `var.security_policy` value set,
expecting it to fallback to `var.security_policy` rather than `null`.
* This didn't work because the module's `backend` variable is an object, which requires that `backend.security_policy` always be set.
1. Test using my …
=> Per-backend security_policy fallback to variable

README.md, autogen/main.tf.tmpl, autogen/variables.tf.tmpl, main.tf, modules/dynamic_backends/README.md, modules/dynamic_backends/main.tf, modules/dynamic_backends/variables.tf, variables.tf
Introduced variables:
- ~~managed_ssl_certificate (bool)~~
- managed_ssl_certificate_domains (list[string])
A managed SSL cert is provisioned only if:
- `ssl` = `true` &&
- `len(var.managed_ssl_certificate_domains) > 0`
- `var.use_ssl_certificates` = `false`.
Similarly, an unmanaged certificate resource (`google_compute_ssl_certificate`)
is not created if ~~`managed_ssl_certificate` is set to `true`~~
`length(var.managed_ssl_certificate_domains)>0`.
I didn't add new test fixtures, however I tested manually with the
`examples/https-redirect` and it succesfully provisioned and served a managed
certificate.
Fixes #96.
cc: @morgante
=> Add managed SSL certificates support

README.md, autogen/README.md, modules/dynamic_backends/README.md, modules/serverless_negs/README.md
The example snippet in README.md files require security_policy field
to be specified. examples/** already employs this practice but the
file didn't reflect that.
=> List required field in generated snippets

README.md, autogen/README.md, modules/dynamic_backends/README.md, modules/serverless_negs/README.md
The old version doesn't support Terraform 1.3.
Fixes #138
=> Bump version in the example to a supported version.

Makefile, README.md, build/int.cloudbuild.yaml, build/lint.cloudbuild.yaml, examples/cloudrun/README.md, examples/https-gke/README.md, examples/https-redirect/README.md, examples/mig-nat-http-lb/README.md, examples/multi-backend-multi-mig-bucket-https-lb/README.md, examples/multi-backend-multi-mig-bucket-https-lb/mig.tf, examples/multi-mig-http-lb/README.md, examples/multiple-certs/README.md, examples/shared-vpc/README.md, modules/dynamic_backends/README.md, modules/serverless_negs/README.md, test/fixtures/cloudrun/versions.tf, test/fixtures/https-redirect/versions.tf, test/fixtures/mig_nat/versions.tf, test/fixtures/multi_certs/versions.tf, test/fixtures/multi_mig/versions.tf, test/setup/main.tf
The CentOS 6 has reached its EOL and is no longer available as a GCE image.
Usually, it should not be an issue, but if for the instance_template module the image_family is set to empty string, terraform considers it as unset and falls back to the centos-6 image family.
This particular example is used for a Qwiklab and this issue is causing the lab to be broken. Specifying an image family/project will fix the lab and the example.
=> add centos 7 source image

autogen/outputs.tf.tmpl, modules/dynamic_backends/outputs.tf, modules/serverless_negs/outputs.tf, outputs.tf
In never versions of terraform, such as 0.14 or 0.15, output values must be marked as sensitive, if they are derived from sensitive fields. This is the case for the `backend_services` output, because it can contain sensitive data (fields `oauth2_client_id` and `oauth2_client_secret` from `iap_config`.
This PR fixes the error:
```
Error: Output refers to sensitive values
on .terraform/modules/lb-http/modules/serverless_negs/outputs.tf line 17:
17: output "backend_services" {
Expressions used in outputs can only refer to sensitive values if the
sensitive attribute is true.
```
After applying this PR, the output generated by `terraform plan` will look like the following:
```
+ resource "google_compute_backend_service" "default" {
+ connection_draining_timeout_sec = (sensitive)
+ …
```
=> Mark output derived from possible sensitive attribute as sensitive

README.md, autogen/main.tf.tmpl, autogen/variables.tf.tmpl, examples/shared-vpc/README.md, examples/shared-vpc/outputs.tf, main.tf, modules/dynamic_backends/README.md, modules/dynamic_backends/main.tf, modules/dynamic_backends/variables.tf, modules/serverless_negs/README.md, modules/serverless_negs/main.tf, modules/serverless_negs/variables.tf, test/setup/.gitignore, test/setup/make_source.sh, variables.tf
This PR implements a random_id suffix on the GCP managed SSL cert, as per the provider documentation . https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_managed_ssl_certificate
This will prevent Terraform trying to remove a certificate that is already in use, when it tries to replace it with a cert of the same name. Has been reported in several issues;
https://github.com/hashicorp/terraform/issues/10546
https://github.com/hashicorp/terraform-provider-google/issues/5356
Tested as working in two separate dev projects.
=> Random cert name

examples/multi-backend-multi-mig-bucket-https-lb/main.tf
Intending to add to another standalone page, similar to https://cloud.devsite.corp.google.com/load-balancing/docs/terraform/ext-http-lb-gce-tf-module
=> Added region tag, module source, and version to bucket example

examples/cloudrun/main.tf
Intending to add snippet to another standalone example page, similar to https://cloud.google.com/load-balancing/docs/terraform/ext-http-lb-gce-tf-module
=> Added region tag, module source, and version to Cloud Run example

autogen/main.tf.tmpl, main.tf, modules/dynamic_backends/main.tf, modules/serverless_negs/main.tf
The option to add a random prefix to the name of the managed certificate
was added as part of #160. When this option is disabled, the `random_id`
resource is still created, despite not being used anywhere. This could
cause confusion when looking at the output of `terraform plan`.
This PR makes the creation of that resource conditional on the
`random_certificate_suffix` flag. When the flag is set to `false`, v5.0
and v6.0 generate the same resources.
(I tried reopening the old PR, but it was not possible, sorry for the mess)
=> Create the `random_id.certificate` resource only when needed.

examples/shared-vpc/README.md, examples/shared-vpc/main.tf
Intending to add to this page:
https://cloud.google.com/load-balancing/docs/https/ext-http-lb-tf-module-examples
=> Added region tags and version for shared VPC LB example

README.md, autogen/README.md, modules/dynamic_backends/README.md, modules/serverless_negs/README.md
Hello, both `modules/dynamic_backends/README.md` and `modules/serverless_negs/README.md` are generated from `autogen/README.md` when running `make build`. But the original `autogen/README.md` seems to suppose only `README.md` on the repository root. This causes the two broken links in two `README.md` under `modules/` directory.
You can see these broken links in the following page:
- [terraform-google-lb-http/modules/dynamic_backends at master · terraform-google-modules/terraform-google-lb-http](https://github.com/terraform-google-modules/terraform-google-lb-http/tree/master/modules/dynamic_backends#resources-created)
- diagram image
- link to the upgrade guide v3
- [terraform-google-lb-http/modules/serverless_negs at master · terraform-google-modules/terraform-google-lb-http](https://githu …
=> fix: Modify the link to the diagram.png and the upgrade guide for 3.0

examples/cloudrun/README.md, examples/cloudrun/main.tf, examples/cloudrun/variables.tf, examples/cloudrun/versions.tf
this PR
1. updates the cloudrun example to share dependencies on the serverless_neg module
2. has the cloudrun example consume the previously unused lb_name variable
=> Update cloudrun example

examples/multi-backend-multi-mig-bucket-https-lb/mig.tf
There's a Cloud Learning Services hands-on lab which follows this example and is experiencing issues. The mig2 and mig3 instances are failing their health checks and the application is unreachable at group2 and group3.
The current template defaults to a Centos7 image and the instances are hitting a file system error and failing to boot past emergency mode. Switching them to ubuntu 18 like mig1 resolves the issue.
=> use ubuntu 18 for mig2 and mig3 templates

autogen/main.tf.tmpl, build/int.cloudbuild.yaml, docs/upgrading_to_v7.0.md, examples/cloudrun/main.tf, metadata.yaml, modules/dynamic_backends/metadata.yaml, modules/serverless_negs/main.tf, modules/serverless_negs/metadata.yaml
- Looks like we forgot to plumb the new values we added in https://github.com/terraform-google-modules/terraform-google-lb-http/pull/287 to the resource
- Adds an upgrade guide
=> fix: plumb backend values, upgrade guide

main.tf, modules/dynamic_backends/main.tf, modules/serverless_negs/main.tf
This will allow a loadbalancer to be built with a certificate_map that also has a frontend with no other certificates specified.
=> fix: Support https frontends with certificate_map

autogen/main.tf.tmpl, main.tf, modules/dynamic_backends/main.tf, modules/serverless_negs/main.tf
This PR fixes a previous commit of mine that used the wrong nested variable in a `dynamic` block. The `cache_key_policy` inside the `outlier_detection` should be `interval` instead.
=> fix: Invalid variable name in outlier_detection block

README.md, autogen/main.tf.tmpl, autogen/variables.tf.tmpl, main.tf, modules/dynamic_backends/README.md, modules/dynamic_backends/main.tf, modules/dynamic_backends/variables.tf, modules/serverless_negs/README.md, modules/serverless_negs/main.tf, modules/serverless_negs/variables.tf, variables.tf
HTTP/S load balancer supports HTTP/S on custom ports. This PR allows specifying ports - [as per documentation exactly one  port from 1-65535](https://cloud.google.com/load-balancing/docs/https?&_ga=2.263917324.-1847637666.1707923371#forwarding-rule).
=> feat: Allow specifying HTTP and HTTPS port.

examples/certificate-map/mig.tf, examples/https-redirect/main.tf, examples/lb-http-separate-frontend-and-backend/mig.tf, examples/multi-backend-multi-mig-bucket-https-lb/mig.tf, examples/multi-mig-http-lb/mig.tf, examples/multiple-certs/mig.tf, examples/user-managed-google-managed-ssl/mig.tf
This PR updates the deprecated `ubuntu-2004-lts` image family to `ubuntu-2204-lts` across the module and example configurations.
- Updated the default value of `source_image_family` inside the `mig-template` module.
- Updated all affected example files to reference `ubuntu-2204-lts` instead of the removed `ubuntu-2004-lts` image family.
The `ubuntu-2004-lts` family has been deprecated and is no longer available in the `ubuntu-os-cloud` GCP project, causing `terraform apply` to fail when running multiple examples from this repository.
- Verified the change by running `terraform plan` and `terraform apply` on updated examples inside my GCP environment.
- Verified the image family `ubuntu-2204-lts` is available via:
```bash
gcloud compute images list --project=ubuntu-os-cloud …
```
=> chore: update all ubuntu image families to ubuntu-2204-lts (fixes #512)
