- main.tf
> added additonal ip ranges to healthcheck rule

- main.tf
- variables.tf
> Disable http forward

- main.tf
- variables.tf
> made the backend protocol a variable instead of hardcoding to HTTP 

- main.tf
- test/integration/multi_certs/controls/https_patterns.rb
* Fixed TF fmt test
* Fixes #60
> Uncomment "group2_region" check in verify test

- README.md
- docs/upgrading-v2.0.0-v3.0.0.md
- main.tf
> Added upgrade guide for v3.0.0

- README.md
Add index of load balancer types across various load balancers in lieu of consolidating to a single repository
> Add index of load balancer types

- README.md
- autogen/README.md
- autogen/main.tf.tmpl
- autogen/variables.tf.tmpl
- main.tf
- modules/dynamic_backends/README.md
- modules/dynamic_backends/main.tf
- modules/dynamic_backends/variables.tf
- variables.tf
> Support target_service_accounts in default firewall rule.

- README.md
- autogen/README.md
- autogen/main.tf.tmpl
- autogen/variables.tf.tmpl
- examples/https-gke/main.tf
- examples/mig-nat-http-lb/main.tf
- examples/multi-backend-multi-mig-bucket-https-lb/main.tf
- examples/multi-mig-http-lb/main.tf
- examples/multiple-certs/main.tf
- examples/shared-vpc/main.tf
- main.tf
- modules/dynamic_backends/README.md
- modules/dynamic_backends/main.tf
- modules/dynamic_backends/variables.tf
- variables.tf
This PR adds support for session affinity on http load balancers which I required for my application
> Add support for session affinity on HTTP(S) LB

- README.md
- autogen/README.md
- autogen/main.tf.tmpl
- autogen/variables.tf.tmpl
- autogen/versions.tf.tmpl
- examples/https-gke/main.tf
- examples/mig-nat-http-lb/main.tf
- examples/multi-backend-multi-mig-bucket-https-lb/main.tf
- examples/multi-mig-http-lb/main.tf
- examples/multiple-certs/main.tf
- examples/shared-vpc/main.tf
- main.tf
- modules/dynamic_backends/README.md
- modules/dynamic_backends/main.tf
- modules/dynamic_backends/variables.tf
- modules/dynamic_backends/versions.tf
- test/fixtures/mig_nat/main.tf
- test/fixtures/multi_certs/main.tf
- test/fixtures/multi_mig/main.tf
- variables.tf
- versions.tf
https://cloud.google.com/load-balancing/docs/health-check-logging
https://github.com/terraform-providers/terraform-provider-google/releases/tag/v3.17.0
3.17 added beta support (we already use beta provider in this module) for setting health check logging, this also means we drop 2.x provider compatibility.
> Add health check logging support

- Makefile
- README.md
- autogen/README.md
- autogen/main.tf.tmpl
- autogen/variables.tf.tmpl
- examples/https-gke/main.tf
- examples/https-redirect/main.tf
- examples/mig-nat-http-lb/main.tf
- examples/multi-backend-multi-mig-bucket-https-lb/main.tf
- examples/multi-mig-http-lb/main.tf
- examples/multiple-certs/main.tf
- examples/shared-vpc/main.tf
- main.tf
- modules/dynamic_backends/README.md
- modules/dynamic_backends/main.tf
- modules/dynamic_backends/variables.tf
- variables.tf
Hi All,
I'm adding the custom request headers into the module as implemented on those links below.
https://cloud.google.com/load-balancing/docs/custom-headers#variables
https://www.terraform.io/docs/providers/google/r/compute_backend_service.html
Please let me know if you have any questions!
> Implementing custom_request_headers 

- README.md
- variables.tf
Hi
I made a small correction of ssl_certificates description.
Thanks !
> Small explanation for ssl_certificates

- autogen/main.tf.tmpl
- main.tf
- modules/dynamic_backends/main.tf
PTAL @morgante @Dev25 @bharathkkb, resolves #142, thank you!
> fix: add hc port of health checked backends to hc-firewall

- examples/https-redirect/README.md
Fix trivial cut and paste error
> Trivial: cut and paste error

- README.md
- autogen/README.md
- modules/dynamic_backends/README.md
- modules/serverless_negs/README.md
> chore: fix broken v4.5.0 link

- examples/multi-mig-http-lb/main.tf
Intending to use on new standalone page for this module.
See cl/383472579.
> Added region tag for inclusion in c.g.c.

- examples/multi-mig-http-lb/README.md
> Updated instructions to verify global forwarding

- examples/https-redirect/README.md
- examples/https-redirect/main.tf
- examples/https-redirect/outputs.tf
Intending to add to https://cloud.google.com/load-balancing/docs/https/ext-http-lb-tf-module-examples
> Added region tags for inclusion on C.G.C. plus minor edits to README and outputs file

- examples/cloudrun/main.tf
> chore: add label to Cloud Run Example

- README.md
- modules/dynamic_backends/variables.tf
> fix: fix description of var load_balancing_scheme

- README.md
- autogen/README.md
- autogen/main.tf.tmpl
- autogen/variables.tf.tmpl
- examples/https-gke/README.md
- examples/https-redirect/README.md
- examples/mig-nat-http-lb/README.md
- examples/multi-backend-multi-mig-bucket-https-lb/README.md
- examples/multi-mig-http-lb/README.md
- examples/multiple-certs/README.md
- main.tf
- modules/dynamic_backends/README.md
- modules/dynamic_backends/main.tf
- modules/dynamic_backends/variables.tf
- modules/serverless_negs/README.md
- modules/serverless_negs/main.tf
- modules/serverless_negs/variables.tf
- variables.tf
> feat: added session affinity for serverless neg

- metadata.display.yaml
- modules/dynamic_backends/metadata.display.yaml
- modules/serverless_negs/metadata.display.yaml
Generate `medadata.display.yaml` file.
> chore: Generate metadata.display.yaml 

- modules/backend/main.tf
- modules/backend/metadata.display.yaml
- modules/frontend/metadata.display.yaml
This PR also updates display metadata for frontend and backend modules.
> fix: support providing null port for creating firewall to support USE_SERVING_PORT
